<?php
// module/Album/view/album/album/add.phtml:

$title = 'Añadir nuevo usuario';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
</br> 
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuarios', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<fieldset>
    <?php
    echo $this->formRow($form->get('id'));
    ?>

    <div class="control-group">
        <?php echo $this->formLabel($form->get('nombre')); ?>
        <div class="controls">
            <?php echo $this->formText($form->get('nombre')); ?>
        </div>
    </div>

    <div class="control-group">
        <?php echo $this->formLabel($form->get('apellidos')); ?>
        <div class="controls">
            <?php echo $this->formTextarea($form->get('apellidos')); ?>
        </div>
    </div>

    <div class="control-group">
        <?php echo $this->formLabel($form->get('email')); ?>
        <div class="controls">
            <?php echo $this->formText($form->get('email')); ?>
        </div>
    </div>

    <div class="control-group">
        <?php echo $this->formLabel($form->get('password')); ?>
        <div class="controls">
            <?php echo $this->formText($form->get('password')); ?>
        </div>
    </div>


    <div class="control-group">
        <?php echo $this->formLabel($form->get('role')); ?>
        <div class="controls">
            <?php echo $this->formText($form->get('role')); ?>
        </div>
    </div>


    <div class="control-group">
        <?php echo $this->formLabel($form->get('estado')); ?>
        <div class="controls">
            <?php echo $this->formText($form->get('estado')); ?>
        </div>
    </div>

    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
</fieldset>
    <?php
    echo $this->form()->closeTag();


    echo "</br> ERRORES:";
    print_r($this->mensajes);
    echo "</br> DATOS FORM:";
    print_r($this->data);